[window]
padding = { x = 5, y = 6 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal = { family = "Hack", style = "Regular" }
italic = { family = "Hack", style = "Regular" }
bold_italic = { family = "Hack", style = "Bold" }
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017"
